use crate::utils;
use base64::Engine;

/// Try downloading with UA negotiation first, then without as fallback
pub async fn download_sub_smart(url: &str) -> anyhow::Result<(String, bool)> {
    // Attempt 1: with Clash UA (most servers return YAML directly)
    let client = reqwest::Client::new();
    let resp = client
        .get(url)
        .header("User-Agent", "clash-verge/2.0.0")
        .send()
        .await?;
    if resp.status().is_success() {
        let content = resp.text().await?;
        if is_clash_yaml(&content) {
            crate::log!("UA negotiation succeeded: got Clash YAML ({} lines)", content.lines().count());
            return Ok((content, true));
        }
        crate::log!("UA negotiation returned non-YAML format ({} bytes), will convert", content.len());
        let is_kind = is_clash_yaml(&content);
        return Ok((content, is_kind));
    }
    // Attempt 2: without UA
    crate::log!("UA negotiation failed (HTTP {}), retrying without UA", resp.status());
    let resp = client.get(url).send().await?;
    let content = resp.text().await?;
    let is_ok = is_clash_yaml(&content);
    Ok((content, is_ok))
}

pub fn is_clash_yaml(content: &str) -> bool {
    content.contains("proxies:") || content.contains("mixed-port:") || content.contains("mode:")
}

pub fn convert_vmess_to_clash(content: &str) -> anyhow::Result<String> {
    let lines = parse_lines(content);

    let mut proxies: Vec<serde_yaml::Value> = Vec::new();

    for line in &lines {
        if line.starts_with("vmess://") {
            if let Some(proxy) = parse_vmess(line) {
                proxies.push(proxy);
            }
        } else if line.starts_with("trojan://") {
            if let Some(proxy) = parse_trojan(line) {
                proxies.push(proxy);
            }
        }
    }

    if proxies.is_empty() {
        anyhow::bail!("No proxies found in subscription");
    }

    let names: Vec<String> = proxies.iter().filter_map(|p| p["name"].as_str().map(String::from)).collect();
    // let names_json = serde_json::to_string(&names)?;

    let controller_line = if cfg!(target_os = "windows") {
        r"external-controller-pipe: \\.\pipe\mihomo"
    } else {
        "external-controller-unix: /tmp/verge/verge-mihomo.sock"
    };

    // Indent the serialized output for proper YAML nesting
    let proxies_yaml = indent(&serde_yaml::to_string(&proxies)?, 2);
    let names_yaml = indent(&serde_yaml::to_string(&names)?, 6);

    let config = format!(
        r#"# Generated by mihomo-cli
mode: rule
mixed-port: 7897
allow-lan: false
log-level: info
ipv6: true
{controller_line}
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
dns:
  enable: true
  listen: 127.0.0.1:1053
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '+.lan'
    - '+.local'
profile:
  store-selected: true

proxies:
{proxies_yaml}

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
{names_yaml}
  - name: 自动选择
    type: url-test
    proxies:
{names_yaml}
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50

rules:
  - MATCH,节点选择
"#,
        proxies_yaml = proxies_yaml,
        names_yaml = names_yaml,
    );

    Ok(config)
}

fn parse_lines(content: &str) -> Vec<String> {
    let raw = content.trim();
    // Check if it starts with protocol prefixes
    for prefix in &["vmess://", "ss://", "trojan://"] {
        if raw.starts_with(prefix) || raw.lines().any(|l| l.starts_with(prefix)) {
            return raw.lines().map(|l| l.trim().to_string()).filter(|l| !l.is_empty()).collect();
        }
    }
    // Try base64 decode
    for pad in &["", "=", "==", "==="] {
        let b64 = format!("{raw}{pad}");
        if let Ok(decoded) = base64::engine::general_purpose::STANDARD.decode(&b64) {
            if let Ok(decoded_str) = String::from_utf8(decoded) {
                return decoded_str.lines().map(|l| l.trim().to_string()).filter(|l| !l.is_empty()).collect();
            }
        }
    }
    raw.lines().map(|l| l.trim().to_string()).filter(|l| !l.is_empty()).collect()
}

fn parse_vmess(line: &str) -> Option<serde_yaml::Value> {
    let b64 = line.strip_prefix("vmess://")?;
    let b64_padded = format!("{}{}", b64, "=".repeat((4 - b64.len() % 4) % 4));
    let json = base64::engine::general_purpose::STANDARD.decode(&b64_padded).ok()?;
    let d: serde_json::Value = serde_json::from_slice(&json).ok()?;

    let name = d["ps"].as_str().unwrap_or("vmess");
    let server = d["add"].as_str().unwrap_or("");
    let port: u64 = d["port"].as_str()?.parse().ok()?;
    let uuid = d["id"].as_str().unwrap_or("");
    let aid: u64 = d["aid"].as_str()?.parse().unwrap_or(0);
    let net = d["net"].as_str().unwrap_or("tcp");
    let tls = d["tls"].as_str().unwrap_or("");

    let mut proxy = serde_yaml::Mapping::new();
    macro_rules! insert {
        ($m:expr, $k:expr, $v:expr) => {
            $m.insert(serde_yaml::Value::String($k.to_string()), serde_yaml::Value::String($v.to_string()));
        };
    }

    insert!(proxy, "name", name);
    insert!(proxy, "type", "vmess");
    insert!(proxy, "server", server);
    insert!(proxy, "port", &port.to_string());
    insert!(proxy, "uuid", uuid);
    insert!(proxy, "alterId", &aid.to_string());
    insert!(proxy, "cipher", "auto");

    if tls == "tls" {
        proxy.insert(serde_yaml::Value::String("tls".into()), serde_yaml::Value::Bool(true));
    }

    if net == "ws" || net == "h2" {
        insert!(proxy, "network", net);
        let mut opts = serde_yaml::Mapping::new();
        if let Some(path) = d["path"].as_str() {
            if !path.is_empty() {
                insert!(opts, "path", path);
            }
        }
        if let Some(host) = d["host"].as_str() {
            if !host.is_empty() {
                let mut headers = serde_yaml::Mapping::new();
                insert!(headers, "Host", host);
                opts.insert(serde_yaml::Value::String("headers".into()), serde_yaml::Value::Mapping(headers));
            }
        }
        if !opts.is_empty() {
            proxy.insert(
                serde_yaml::Value::String(format!("{net}-opts")),
                serde_yaml::Value::Mapping(opts),
            );
        }
    } else if net == "grpc" {
        insert!(proxy, "network", "grpc");
        let mut opts = serde_yaml::Mapping::new();
        let svc = d["path"].as_str().unwrap_or("").trim_start_matches('/');
        if !svc.is_empty() {
            insert!(opts, "grpc-service-name", svc);
            proxy.insert(
                serde_yaml::Value::String("grpc-opts".into()),
                serde_yaml::Value::Mapping(opts),
            );
        }
    } else if !net.is_empty() {
        insert!(proxy, "network", net);
    }

    Some(serde_yaml::Value::Mapping(proxy))
}

fn parse_trojan(line: &str) -> Option<serde_yaml::Value> {
    let rest = line.strip_prefix("trojan://")?;
    let at_idx = rest.find('@')?;
    let password = &rest[..at_idx];
    let after_at = &rest[at_idx + 1..];
    let qm = after_at.find('?').unwrap_or(after_at.len());
    let host_port = &after_at[..qm];
    let (host, port_str) = host_port.rsplit_once(':')?;
    let port: u64 = port_str.parse().ok()?;

    let _query = if qm < after_at.len() { &after_at[qm + 1..] } else { "" };

    let mut proxy = serde_yaml::Mapping::new();
    macro_rules! insert {
        ($m:expr, $k:expr, $v:expr) => {
            $m.insert(serde_yaml::Value::String($k.to_string()), serde_yaml::Value::String($v.to_string()));
        };
    }

    insert!(proxy, "name", "trojan");
    insert!(proxy, "type", "trojan");
    insert!(proxy, "server", host);
    insert!(proxy, "port", &port.to_string());
    insert!(proxy, "password", password);

    Some(serde_yaml::Value::Mapping(proxy))
}

pub fn save_config(content: &str) -> anyhow::Result<()> {
    let dir = utils::config_dir();
    std::fs::create_dir_all(&dir)?;
    let path = utils::config_path();

    // Ensure the config has external-controller setup
    let content = ensure_controller(content);

    std::fs::write(&path, &content)?;
    println!("Config saved to {path}");
    Ok(())
}

/// Fix the existing config file: ensure it has external-controller-unix/pipe.
/// Reads current config, applies ensure_controller(), writes back.
/// Returns true if the file was modified.
pub fn fix_existing_config() -> bool {
    let path = crate::utils::config_path();
    let content = match std::fs::read_to_string(&path) {
        Ok(c) => c,
        Err(_) => return false,
    };
    let fixed = ensure_controller(&content);
    if fixed == content {
        return false; // No change needed
    }
    std::fs::write(&path, &fixed).is_ok()
}

/// Add external-controller-unix/pipe if missing from the config
pub(crate) fn ensure_controller(yaml: &str) -> String {
    let controller = if cfg!(target_os = "windows") {
        "external-controller-pipe: \\\\.\\pipe\\mihomo"
    } else {
        "external-controller-unix: /tmp/verge/verge-mihomo.sock"
    };

    // Already has Unix socket or pipe — nothing to do
    if yaml.contains("external-controller-unix") || yaml.contains("external-controller-pipe") {
        return yaml.to_string();
    }

    let mut lines: Vec<String> = yaml.lines().map(|l| l.to_string()).collect();

    // Replace existing HTTP `external-controller:` with Unix socket
    let mut replaced = false;
    for line in lines.iter_mut() {
        if line.starts_with("external-controller:") {
            *line = controller.to_string();
            replaced = true;
            break;
        }
    }

    if !replaced {
        // Insert after the first line that is not mode/mixed-port/ipv6
        let mut inserted = false;
        for (i, line) in lines.clone().iter().enumerate() {
            if line.starts_with("mode:") || line.starts_with("mixed-port:") || line.starts_with("ipv6:") {
                continue;
            }
            lines.insert(i, controller.to_string());
            inserted = true;
            break;
        }
        if !inserted {
            lines.push(controller.to_string());
        }
    }

    lines.join("\n")
}

pub fn check_config_exists() -> bool {
    std::path::Path::new(&utils::config_path()).exists()
}

fn indent(s: &str, spaces: usize) -> String {
    let prefix = " ".repeat(spaces);
    s.lines().map(|l| if l.is_empty() { String::new() } else { format!("{prefix}{l}") })
        .collect::<Vec<_>>().join("\n")
}

